server:
#  port: 7900
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
     defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true # 把自己的IP注册到Eureka上面去
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} # 修改Status显示
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:date.sql
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.fyyzi: debug