server:
  port: 7901
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance: # 把自己的IP注册到Eureka上面去
#    prefer-ip-address: true
spring:
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.fyyzi: debug
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 把自己的IP注册到Eureka上面去
    healthcheck:
      enabled: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} # 修改Status显示
#MICROSERVICE-PROVIDER-USER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netfix.loadbalancer.RandomRule
